/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LocalSearch {
    'linkText': string;
    'mapUrl': string;
    'titleText': string;
  }
  interface OfferBlockTile {}
  interface RedemptionButton {
    'modalUrl'?: string;
    'offerId': number;
    'redirectUrl'?: string;
  }
}

declare global {


  interface HTMLLocalSearchElement extends Components.LocalSearch, HTMLStencilElement {}
  var HTMLLocalSearchElement: {
    prototype: HTMLLocalSearchElement;
    new (): HTMLLocalSearchElement;
  };

  interface HTMLOfferBlockTileElement extends Components.OfferBlockTile, HTMLStencilElement {}
  var HTMLOfferBlockTileElement: {
    prototype: HTMLOfferBlockTileElement;
    new (): HTMLOfferBlockTileElement;
  };

  interface HTMLRedemptionButtonElement extends Components.RedemptionButton, HTMLStencilElement {}
  var HTMLRedemptionButtonElement: {
    prototype: HTMLRedemptionButtonElement;
    new (): HTMLRedemptionButtonElement;
  };
  interface HTMLElementTagNameMap {
    'local-search': HTMLLocalSearchElement;
    'offer-block-tile': HTMLOfferBlockTileElement;
    'redemption-button': HTMLRedemptionButtonElement;
  }
}

declare namespace LocalJSX {
  interface LocalSearch {
    'linkText'?: string;
    'mapUrl'?: string;
    'titleText'?: string;
  }
  interface OfferBlockTile {}
  interface RedemptionButton {
    'modalUrl'?: string;
    'offerId'?: number;
    'onOnRedemption'?: (event: CustomEvent<any>) => void;
    'redirectUrl'?: string;
  }

  interface IntrinsicElements {
    'local-search': LocalSearch;
    'offer-block-tile': OfferBlockTile;
    'redemption-button': RedemptionButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'local-search': LocalJSX.LocalSearch & JSXBase.HTMLAttributes<HTMLLocalSearchElement>;
      'offer-block-tile': LocalJSX.OfferBlockTile & JSXBase.HTMLAttributes<HTMLOfferBlockTileElement>;
      'redemption-button': LocalJSX.RedemptionButton & JSXBase.HTMLAttributes<HTMLRedemptionButtonElement>;
    }
  }
}


